CREATE TABLE IF NOT EXISTS users(
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                        fname VARCHAR(255) ,
    lname VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL ,
    password_hash bytea NOT NULL ,
    user_role VARCHAR(50),
    activated bool NOT NULL
    );